'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Search,Bell,Clock,Globe} from 'lucide-react';
import UserMenu from '@/components/auth/user-menu';
import {api,useApi,Dialog,inputClass} from '@/components/platform/client';
export function TopNav({health}){
 const [clock,setClock]=useState(''),[search,setSearch]=useState(false),[query,setQuery]=useState(''),[notifications,setNotifications]=useState(false),[error,setError]=useState('');const data=useApi('/api/notifications?pageSize=25',false,10000);
 useEffect(()=>{const tick=()=>setClock(new Date().toLocaleTimeString());tick();const timer=setInterval(tick,1000);const shortcut=e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setSearch(s=>!s);}};window.addEventListener('keydown',shortcut);return()=>{clearInterval(timer);window.removeEventListener('keydown',shortcut);};},[]);
 return <><header className="sticky top-0 z-30 h-16 bg-[#070B14]/90 backdrop-blur-md border-b border-[#1E293B] px-4 md:px-6 flex items-center justify-between gap-3"><button className="ml-10 md:ml-0 gs-secondary !py-2 flex gap-2 items-center text-xs" onClick={()=>setSearch(true)}><Search size={15}/><span className="hidden sm:inline">Search traffic / ⌘K</span></button><div className="flex items-center gap-3"><Link className="hidden xl:flex text-xs text-slate-400 items-center gap-1" href="/"><Globe size={14}/>Public site</Link><span className="hidden lg:flex gap-2 text-xs text-slate-400"><Clock size={14}/>{clock}</span><span className="hidden md:inline text-xs text-cyan-400">{health?.database==='AVAILABLE'?'Backend connected':'Checking health…'}</span><button className="gs-secondary !p-2 relative" aria-label="Notifications" onClick={()=>setNotifications(true)}><Bell size={16}/>{data.data?.items?.some(n=>!n.read)&&<span className="absolute top-1 right-1 w-2 h-2 bg-cyan-400 rounded-full"/>}</button><UserMenu/></div></header>
 {search&&<Dialog title="Search security events" onClose={()=>setSearch(false)}><form onSubmit={e=>{e.preventDefault();window.location.assign('/live-traffic?q='+encodeURIComponent(query)+'&range=all');}} className="space-y-3"><input aria-label="Search IP or request" autoFocus className={inputClass} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Source IP or request path"/><button className="gs-primary">Search traffic</button></form></Dialog>}
 {notifications&&<Dialog title="Notifications" onClose={()=>setNotifications(false)}>{(error||data.error)&&<p role="alert">{error||data.error}</p>}{!data.data?.items?.length&&<p className="text-sm text-slate-400">No notifications yet.</p>}<ul className="space-y-3">{data.data?.items?.map(n=><li key={n.id} className="rounded-xl p-3 border border-slate-700"><p className="text-sm font-semibold">{n.title}</p><p className="text-xs text-slate-400 my-2">{n.message}</p><span className="text-xs text-slate-500">{new Date(n.createdAt).toLocaleString()}</span>{!n.read&&<button className="text-xs text-cyan-400 ml-3" onClick={async()=>{try{await api('/api/notifications/'+n.id,{method:'PATCH',body:JSON.stringify({read:true})});await data.refresh();}catch(e){setError(e.message);}}}>Mark read</button>}</li>)}</ul></Dialog>}</>;
}
