'use client';
import { useCallback,useEffect,useRef,useState } from 'react';
export async function api(url,options={}) {const r=await fetch(url,{cache:'no-store',...options,headers:{...(options.body?{'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()}:{}),...options.headers}});const data=await r.json();if(!r.ok){const details=Object.entries(data.fields||{}).map(([field,messages])=>field+': '+messages.join(' ')).join(' ');throw new Error(details||data.error||'Request failed.');}return data;}
export function useApi(url,paused=false,interval=5000) {
 const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);const generation=useRef(0);
 const invalidate=useCallback(()=>{generation.current++;},[]);
 const refresh=useCallback(async()=>{const version=++generation.current;try{const result=await api(url);if(version===generation.current){setData(result);setError('');}}catch(e){if(version===generation.current)setError(e.message);}finally{if(version===generation.current)setLoading(false);}},[url]);
 useEffect(()=>{setLoading(true);refresh();if(paused)return;let stopped=false,timer;const poll=()=>{timer=setTimeout(async()=>{if(document.visibilityState==='visible')await refresh();if(!stopped)poll();},interval);};poll();return()=>{stopped=true;clearTimeout(timer);invalidate();};},[refresh,paused,interval,invalidate]);
 return {data,error,loading,refresh};
}
export const inputClass='w-full rounded-xl border border-[#1E293B] bg-[#070B14] px-3 py-2 text-sm text-slate-100 focus:outline-none focus:border-cyan-400';
export function Empty({children='No records in this range. Connect an asset or start an administrator simulation.'}){return <p className="p-8 text-center text-sm text-slate-400">{children}</p>}
export function Loading(){return <div role="status" aria-label="Loading" className="space-y-3 animate-pulse">{[1,2,3].map(i=><div key={i} className="h-16 rounded-xl bg-slate-800/60"/>)}</div>}
export function Badge({children}){return <span className="inline-flex rounded-md border border-cyan-500/20 bg-cyan-500/10 px-2 py-1 text-xs font-mono text-cyan-300">{children}</span>}
export function Card({title,children}){return <section className="rounded-xl bg-[#111827] border border-[#1E293B] p-4 sm:p-5 shadow-card min-w-0"><h2 className="text-base font-semibold text-white mb-4">{title}</h2>{children}</section>}
export function Field({name,label,type='text',options,defaultValue,required=true,min,max,disabled=false}){return <label className="block text-xs text-slate-400 space-y-2"><span>{label}</span>{options?<select name={name} defaultValue={defaultValue} required={required} disabled={disabled} className={inputClass}>{options.map(o=><option key={o} value={o}>{o}</option>)}</select>:type==='textarea'?<textarea className={inputClass} name={name} defaultValue={defaultValue} required={required} maxLength={4000}/>:<input className={inputClass} name={name} type={type} defaultValue={defaultValue} required={required} min={min} max={max} disabled={disabled}/>}</label>}
export function Table({items,columns,onOpen}){if(!items?.length)return <Empty/>;return <div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-slate-400 border-b border-slate-700"><tr>{columns.map(([key,label])=><th key={key} className="px-3 py-3 whitespace-nowrap">{label}</th>)}{onOpen&&<th className="px-3">Details</th>}</tr></thead><tbody>{items.map(row=><tr key={row.id} className="border-b border-slate-800 hover:bg-slate-800/40">{columns.map(([key,,render])=><td key={key} className="px-3 py-3 max-w-xs break-words">{render?render(row):String(row[key]??'—')}</td>)}{onOpen&&<td className="px-3"><button className="text-cyan-400 hover:underline" onClick={()=>onOpen(row)}>Open</button></td>}</tr>)}</tbody></table></div>}
export function Dialog({title,children,onClose}){const ref=useRef();useEffect(()=>{const dialog=ref.current;dialog.showModal();return()=>dialog.close();},[]);return <dialog ref={ref} onCancel={onClose} className="w-[min(95vw,760px)] max-h-[90vh] overflow-y-auto p-0 rounded-2xl bg-[#0B1220] text-slate-100 border border-slate-700 backdrop:bg-black/80"><div className="sticky top-0 z-10 bg-[#0B1220] p-5 border-b border-slate-700 flex justify-between"><h2 className="font-mono text-lg">{title}</h2><button aria-label="Close dialog" className="gs-secondary !py-1" onClick={onClose}>Close</button></div><div className="p-5 space-y-4">{children}</div></dialog>}
