'use client';
import {useState} from 'react';
import Link from 'next/link';
import {api,useApi,Card,Field,Table,Dialog,Loading} from './client';
export function SettingsPanel({user,onMessage}) {
 const settings=useApi('/api/settings',true),assets=useApi('/api/assets',true),keys=useApi('/api/api-keys',true),audit=useApi('/api/audit-logs',true);const [busy,setBusy]=useState(false),[secret,setSecret]=useState(''),[asset,setAsset]=useState(null),[confirm,setConfirm]=useState(null);
 const admin=user?.role?.toUpperCase()==='ADMIN',manage=['ADMIN','ANALYST'].includes(user?.role?.toUpperCase());
 async function save(url,data,method='POST'){setBusy(true);try{const result=await api(url,{method,body:JSON.stringify(data)});onMessage('Saved successfully.');setAsset(null);setConfirm(null);await Promise.all([settings.refresh(),assets.refresh(),keys.refresh(),audit.refresh()]);return result;}catch(e){onMessage(e.message);return null;}finally{setBusy(false);}}
 return <div className="space-y-5"><Card title="Profile settings"><p className="text-sm text-slate-400 mb-4">Update your existing account’s name, image, username and professional information.</p><Link href="/profile" className="gs-secondary inline-block">Edit profile</Link></Card>
 {settings.error&&<p role="alert" className="text-red-300">{settings.error}</p>}
 {settings.loading?<Loading/>:settings.data&&<Card title="Detection, notifications and preferences"><form className="space-y-5" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const data={...settings.data};delete data.userId;delete data.updatedAt;for(const k of ['detectionSensitivity','monitorThreshold','divertThreshold','blockThreshold','retentionDays'])if(f.has(k))data[k]=Number(f.get(k));data.theme=f.get('theme');data.notificationPreferences={alerts:f.get('alerts')==='on',simulation:f.get('simulation')==='on'};if(admin)data.ghostDefaults={operatingSystem:f.get('operatingSystem'),serviceTemplate:f.get('serviceTemplate'),loggingLevel:f.get('loggingLevel')};save('/api/settings',data,'PATCH').then(result=>{if(result){localStorage.setItem('decevia-theme',result.theme);window.dispatchEvent(new Event('decevia-theme'));}});}}>
 <fieldset disabled={!manage||busy} className="space-y-5"><div className="flex flex-wrap gap-5 text-sm"><label className="flex gap-2"><input name="alerts" type="checkbox" defaultChecked={settings.data.notificationPreferences.alerts}/>Alert notifications</label><label className="flex gap-2"><input name="simulation" type="checkbox" defaultChecked={settings.data.notificationPreferences.simulation}/>Simulation notifications</label></div>
 <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4"><Field name="detectionSensitivity" label="Detection sensitivity (0–100)" type="number" min={0} max={100} defaultValue={settings.data.detectionSensitivity} disabled={!admin}/><Field name="monitorThreshold" label="Monitor threshold" type="number" min={1} max={98} defaultValue={settings.data.monitorThreshold} disabled={!admin}/><Field name="divertThreshold" label="Divert threshold" type="number" min={2} max={99} defaultValue={settings.data.divertThreshold} disabled={!admin}/><Field name="blockThreshold" label="Block threshold" type="number" min={3} max={100} defaultValue={settings.data.blockThreshold} disabled={!admin}/><Field name="retentionDays" label="Data retention days" type="number" min={1} max={3650} defaultValue={settings.data.retentionDays} disabled={!admin}/><Field name="theme" label="Theme preference" defaultValue={settings.data.theme} options={['dark','light','system']}/></div>
 <h3 className="text-sm text-cyan-300">Ghost environment defaults</h3><div className="grid sm:grid-cols-3 gap-4"><Field name="operatingSystem" label="Operating system" defaultValue={settings.data.ghostDefaults.operatingSystem} disabled={!admin} options={['Ubuntu 24.04','Windows Server 2022','Debian 12']}/><Field name="serviceTemplate" label="Service" defaultValue={settings.data.ghostDefaults.serviceTemplate} disabled={!admin} options={['HTTP','SSH','Database','Identity']}/><Field name="loggingLevel" label="Logging" defaultValue={settings.data.ghostDefaults.loggingLevel} disabled={!admin} options={['STANDARD','VERBOSE']}/></div><p className="text-xs text-slate-400">Retention is a saved policy. Run the documented maintenance command to remove expired telemetry; saving settings does not delete data.</p><button disabled={busy} className="gs-primary">{busy?'Saving…':'Save settings'}</button></fieldset></form></Card>}
 <Card title="Connected protected assets"><Table items={assets.data?.items} columns={[["name","Name"],["hostname","Hostname"],["assetType","Type"],["status","Status"],["simulated","Simulated",r=>r.simulated?'Yes':'No']]} onOpen={admin?r=>setAsset(r):undefined}/>{admin&&<button className="gs-primary mt-4" onClick={()=>setAsset({})}>Add protected asset</button>}</Card>
 {admin&&<Card title="Ingestion API keys"><p className="text-xs text-slate-400 mb-4">Keys can ingest events for your real assets. Secrets are shown once, stored as SHA-256 hashes, and never returned in key listings.</p>{keys.error&&<p className="text-red-300">{keys.error}</p>}<Table items={keys.data?.items} columns={[["name","Name"],["prefix","Prefix"],["createdAt","Created",r=>new Date(r.createdAt).toLocaleString()],["revokedAt","State",r=>r.revokedAt?'Revoked':<button disabled={busy} className="text-red-300" onClick={()=>setConfirm(r)}>Revoke</button>]]}/><form className="flex flex-wrap items-end gap-3 mt-4" onSubmit={async e=>{e.preventDefault();const result=await save('/api/api-keys',Object.fromEntries(new FormData(e.currentTarget)));if(result?.key)setSecret(result.key);}}><Field name="name" label="API key name"/><button className="gs-primary" disabled={busy}>Generate key</button></form>{secret&&<div className="mt-4 space-y-2"><p className="text-sm text-amber-300">Copy this key now. It cannot be retrieved again.</p><code className="block break-all bg-slate-950 rounded-lg p-3 text-xs">{secret}</code><button className="gs-secondary" onClick={()=>{navigator.clipboard.writeText(secret).then(()=>onMessage('Key copied.')).catch(()=>onMessage('Select and copy the key manually.'));}}>Copy key</button><button className="gs-secondary ml-2" onClick={()=>setSecret('')}>Hide key</button></div>}</Card>}
 <Card title="Audit history"><Table items={audit.data?.items} columns={[["createdAt","Time",r=>new Date(r.createdAt).toLocaleString()],["action","Action"],["resourceType","Resource"],["resourceId","Record"]]}/></Card>
 {asset&&<Dialog title={asset.id?'Edit protected asset':'Add protected asset'} onClose={()=>setAsset(null)}><form className="space-y-4" onSubmit={e=>{e.preventDefault();save('/api/assets'+(asset.id?'/'+asset.id:''),Object.fromEntries(new FormData(e.currentTarget)),asset.id?'PATCH':'POST');}}><Field name="name" label="Name" defaultValue={asset.name}/><Field name="assetType" label="Asset type" options={['WEB','API','DATABASE','IDENTITY','HOST']} defaultValue={asset.assetType}/><Field name="hostname" label="Hostname" defaultValue={asset.hostname}/><Field name="maskedIpAddress" label="Masked IP address" defaultValue={asset.maskedIpAddress}/><Field name="operatingSystem" label="Operating system" defaultValue={asset.operatingSystem}/><Field name="environment" label="Environment" options={['PRODUCTION','STAGING','DEVELOPMENT']} defaultValue={asset.environment}/><Field name="status" label="Status" options={['ACTIVE','INACTIVE']} defaultValue={asset.status}/><button className="gs-primary" disabled={busy}>Save asset</button></form></Dialog>}
 {confirm&&<Dialog title="Revoke API key?" onClose={()=>setConfirm(null)}><p>This immediately stops ingestion using this key.</p><button className="gs-primary" disabled={busy} onClick={()=>save('/api/api-keys/'+confirm.id,{confirm:true},'DELETE')}>Confirm revocation</button></Dialog>}
 </div>;
}
