'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {getSession} from 'next-auth/react';
import {Activity,Shield,Terminal,Server,AlertTriangle,ShieldCheck,RefreshCw,Download,Plus,Pause,Play} from 'lucide-react';
import {DashboardShell} from '@/components/layout/dashboard-shell';
import {StatCard} from '@/components/ui/stat-card';
import {TerminalReplay} from '@/components/sessions/terminal-replay';
import {api,useApi,Card,Field,Table,Dialog,Empty,Loading,Badge,inputClass} from './client';
import {Chart} from './charts';
import {SettingsPanel} from './settings';
const titles={dashboard:'Security Command Center',traffic:'Live Traffic',sessions:'Attack Sessions',environments:'Ghost Environments',intelligence:'Threat Intelligence',alerts:'Security Alerts',architecture:'System Architecture',reports:'Security Reports',settings:'Platform Settings'};
const endpoints={traffic:'traffic',sessions:'attack-sessions',environments:'ghost-environments',alerts:'alerts',reports:'reports',intelligence:'threat-intelligence/indicators'};
const time=value=>value?new Date(value).toLocaleString():'—';
const columns={traffic:[['timestamp','Time',r=>time(r.timestamp)],['sourceIp','Source IP'],['sourceCountry','Country'],['requestPath','Request'],['riskScore','Risk'],['decision','Decision'],['status','Status'],['simulated','Mode',r=>r.simulated?'Simulated':'Sensor']],sessions:[['sessionCode','Session'],['sourceIp','Source'],['attackType','Attack Type'],['riskScore','Risk'],['status','Status'],['startedAt','Started',r=>time(r.startedAt)]],environments:[['name','Environment'],['operatingSystem','OS'],['serviceTemplate','Service'],['status','Status'],['isolationStatus','Isolation'],['cpuUsage','CPU %'],['memoryUsage','Memory %']],alerts:[['title','Alert'],['severity','Severity'],['status','Status'],['source','Source'],['createdAt','Created',r=>time(r.createdAt)]],reports:[['name','Report'],['reportType','Type'],['status','Status'],['dateFrom','From',r=>time(r.dateFrom)],['dateTo','To',r=>time(r.dateTo)]],intelligence:[['value','Indicator'],['severity','Severity'],['confidence','Confidence %'],['occurrenceCount','Occurrences'],['firstSeen','First Seen',r=>time(r.firstSeen)],['lastSeen','Last Seen',r=>time(r.lastSeen)]]};
export default function Workspace({view}) {
 const [user,setUser]=useState(null),[filters,setFilters]=useState({range:'7d',page:'1'}),[paused,setPaused]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[selected,setSelected]=useState(null),[create,setCreate]=useState(false),[confirm,setConfirm]=useState(null),[speed,setSpeed]=useState(1);
 useEffect(()=>{getSession().then(s=>setUser(s?.user));const params=Object.fromEntries(new URLSearchParams(window.location.search));setFilters(f=>({...f,...params}));},[]);
 const role=user?.role?.toUpperCase(),admin=role==='ADMIN',manage=admin||role==='ANALYST';
 function filter(key,value){setFilters(old=>{const next={...old,[key]:value,...(key!=='page'?{page:'1'}:{}),...(key==='range'&&value==='custom'?{from:old.from||new Date(Date.now()-7*86400000).toISOString(),to:old.to||new Date().toISOString()}:{})};if(!value)delete next[key];const query=new URLSearchParams(next).toString();window.history.replaceState(null,'','?'+query);return next;});}
 const query=new URLSearchParams(filters).toString();
 const collection=useApi('/api/'+(endpoints[view]||'dashboard/summary')+'?'+query,paused);
 const health=useApi('/api/dashboard/system-health',paused,10000);
 const simulation=useApi('/api/simulation',false,10000);
 const preferences=useApi('/api/settings',true);
 const charts=useApi('/api/'+(view==='intelligence'?'threat-intelligence/summary':'dashboard/charts')+'?'+query,paused,10000);
 const recent=useApi('/api/dashboard/recent-events?'+query,paused,10000);
 async function refresh(){await Promise.all([collection.refresh(),health.refresh(),charts.refresh(),recent.refresh(),simulation.refresh()]);}
 async function mutation(url,data={},method='POST',close=true){setBusy(true);setMessage('');try{const result=await api(url,{method,body:JSON.stringify(data)});setMessage('Saved successfully.');if(close){setCreate(false);setSelected(null);setConfirm(null);}await refresh();return result;}catch(e){setMessage(e.message);return null;}finally{setBusy(false);}}
 useEffect(()=>{if(!admin||!simulation.data?.running||!simulation.data?.enabled)return;let stopped=false,timer;const tick=()=>{timer=setTimeout(async()=>{try{await api('/api/simulation',{method:'POST',body:JSON.stringify({action:'tick'})});}catch(e){if(!stopped)setMessage(e.message);}if(!stopped)tick();},5000);};tick();return()=>{stopped=true;clearTimeout(timer);};},[admin,simulation.data?.running,simulation.data?.enabled]);
 async function open(row){setBusy(true);setMessage('');try{if(view==='intelligence'){setSelected(row);return;}setSelected(await api('/api/'+endpoints[view]+'/'+row.id));}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 const data=collection.data,stats=view==='dashboard'?data:null,chartData=charts.data;
 return <DashboardShell><div className="space-y-6">
 <header className="flex flex-wrap justify-between gap-4"><div><p className="text-xs font-mono text-cyan-400 uppercase tracking-widest mb-2">Decevia / Defensive Operations</p><h1 className="font-mono text-2xl sm:text-3xl font-bold">{titles[view]}</h1><p className="text-sm text-slate-400 mt-2">Your workspace · {user?.name||'Loading account…'} · {role||'…'}</p></div><div className="flex items-center gap-2"><button aria-label="Refresh data" disabled={busy} className="gs-secondary" onClick={refresh}><RefreshCw size={16}/></button><button className="gs-secondary flex gap-2 items-center" onClick={()=>setPaused(!paused)}>{paused?<Play size={15}/>:<Pause size={15}/>} {paused?'Resume updates':'Pause updates'}</button></div></header>
 {message&&<p role="status" className="rounded-xl border border-cyan-500/30 bg-cyan-500/10 text-cyan-200 p-3 text-sm">{message}</p>}
 {(collection.error||health.error||charts.error)&&<p role="alert" className="p-4 border border-red-500/40 rounded-xl text-red-300">{collection.error||health.error||charts.error} Updates retry automatically.</p>}
 {view!=='settings'&&<div className="flex flex-wrap items-end gap-3 rounded-xl bg-[#111827] border border-[#1E293B] p-4"><label className="text-xs text-slate-400">Date range (UTC)<select aria-label="Date range" className={inputClass} value={filters.range} onChange={e=>filter('range',e.target.value)}><option value="today">Today</option><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option><option value="custom">Custom</option><option value="all">All time</option></select></label>{filters.range==='custom'&&['from','to'].map(key=><label key={key} className="text-xs text-slate-400">{key}<input aria-label={key} type="datetime-local" className={inputClass} value={filters[key]?.slice(0,16)||''} onChange={e=>filter(key,e.target.value?e.target.value+':00.000Z':'')}/></label>)}{endpoints[view]&&<><label className="text-xs text-slate-400">Search<input className={inputClass} value={filters.q||''} onChange={e=>filter('q',e.target.value)} placeholder={view==='traffic'?'Source IP or request':'Search records'}/></label>{['traffic','sessions'].includes(view)&&<label className="text-xs text-slate-400">Minimum risk<input className={inputClass+' max-w-28'} type="number" min="0" max="100" value={filters.riskMin||0} onChange={e=>filter('riskMin',e.target.value)}/></label>}{view==='traffic'&&<><FilterSelect label="Decision" value={filters.decision} options={['ALLOW','MONITOR','DIVERT','BLOCK']} onChange={v=>filter('decision',v)}/><label className="text-xs text-slate-400">Country<input className={inputClass+' max-w-40'} value={filters.country||''} onChange={e=>filter('country',e.target.value)}/></label><FilterSelect label="Sort" value={filters.sort||'timestamp'} options={['timestamp','riskScore','sourceIp']} onChange={v=>filter('sort',v)}/><FilterSelect label="Order" value={filters.order||'desc'} options={['desc','asc']} onChange={v=>filter('order',v)}/><a className="gs-secondary inline-flex gap-2" href={'/api/traffic/export?'+query}><Download size={16}/>CSV</a></>}{['traffic','sessions','alerts','environments'].includes(view)&&<FilterSelect label="Status" value={filters.status} options={view==='traffic'?['OBSERVED','DIVERTED','BLOCKED','NO_ENVIRONMENT','RECOMMENDED']:view==='sessions'?['ACTIVE','COMPLETED']:view==='alerts'?['OPEN','INVESTIGATING','RESOLVED']:['RUNNING','STOPPED']} onChange={v=>filter('status',v)}/>} {view==='sessions'&&<label className="text-xs text-slate-400">Attack type<input className={inputClass} value={filters.attackType||''} onChange={e=>filter('attackType',e.target.value)}/></label>}{view==='alerts'&&<FilterSelect label="Severity" value={filters.severity} options={['LOW','MEDIUM','HIGH','CRITICAL']} onChange={v=>filter('severity',v)}/>}</>}{((view==='environments'&&admin)||(view==='reports'&&manage))&&<button disabled={busy} className="gs-primary inline-flex items-center gap-2" onClick={()=>setCreate(true)}><Plus size={16}/>{view==='reports'?'Generate report':'Create environment'}</button>}</div>}
 {view==='dashboard'&&<>
 <div className="p-4 rounded-xl border border-cyan-500/30 bg-gradient-to-r from-[#0B1220] to-[#111827] flex flex-wrap items-center justify-between gap-4"><div className="flex gap-3 items-center"><ShieldCheck className="text-cyan-400"/><div><p className="font-semibold">{health.data?.activeAssets??0} protected assets configured</p><p className="text-xs text-slate-400 mt-1">Sensor events produce recommendations. Ghost isolation and diversion are simulated in this version.</p></div></div><Badge>{simulation.data?.running?'SIMULATION RUNNING':'MONITORING'}</Badge></div>
 {admin&&<Card title="Safe simulation"><div className="flex flex-wrap gap-3 items-center"><select aria-label="Simulation speed" className={inputClass+' !w-auto'} value={speed} onChange={e=>setSpeed(Number(e.target.value))}>{[1,3,5,10].map(n=><option key={n} value={n}>{n} events / 5 seconds</option>)}</select><button disabled={busy||!simulation.data?.enabled} className="gs-primary" onClick={()=>mutation('/api/simulation',{action:'start',speed})}>Start Simulation</button><button disabled={busy||!simulation.data?.running} className="gs-secondary" onClick={()=>mutation('/api/simulation',{action:'stop'})}>Stop Simulation</button><button disabled={busy||!simulation.data?.enabled} className="gs-secondary text-red-300" onClick={()=>setConfirm({title:'Clear simulated data?',description:'Stops simulation and removes your simulated records. Real records are preserved.',url:'/api/simulation',data:{action:'clear',confirm:true},method:'POST'})}>Clear Simulated Data</button></div><p className="text-xs text-slate-400 mt-3">{simulation.data?.enabled?'Generation runs while an administrator dashboard is open. All generated records are labelled simulated.':'Set SIMULATION_MODE=true in the server environment to enable simulation.'}</p></Card>}
 {collection.loading?<Loading/>:stats&&<div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">{[['Total Traffic Analysed','totalTraffic',Activity,'cyan'],['Threats Diverted','threatsDiverted',Shield,'violet'],['Active Ghost Sessions','activeGhostSessions',Terminal,'cyan'],['Protected Systems','protectedSystems',Server,'emerald'],['Critical Alerts','criticalAlerts',AlertTriangle,'rose'],['Diversion Success Rate','diversionSuccessRate',ShieldCheck,'emerald']].map(([title,key,icon,accentColor])=><StatCard key={key} title={title} value={stats[key]+(key==='diversionSuccessRate'?'%':'')} icon={icon} accentColor={accentColor} sparklineData={[]} tooltip="Calculated from records owned by your account. Event metrics use the selected date range."/>)}</div>}
 <ChartGrid data={chartData}/>
 <Card title="Recent security events"><Table items={recent.data?.events} columns={columns.traffic}/><Link href="/live-traffic" className="text-cyan-400 text-xs">Investigate live traffic →</Link></Card>
 <div className="grid lg:grid-cols-2 gap-5"><Card title="Active attacker sessions"><Table items={recent.data?.sessions} columns={columns.sessions.slice(1,5)}/><Link className="text-cyan-400 text-xs" href="/attack-sessions">Open sessions →</Link></Card><Card title="Recent critical alerts"><Table items={recent.data?.alerts} columns={columns.alerts.slice(0,3)}/><Link className="text-cyan-400 text-xs" href="/alerts">Investigate alerts →</Link></Card></div><Health data={health.data}/>
 </>}
 {view==='architecture'&&<><p className="text-sm text-slate-400">Health reflects stored activity and simulator state. No physical sandbox or network diversion is provisioned.</p><Health data={health.data}/></>}
 {view==='intelligence'&&<ChartGrid data={chartData} intelligence/>}
 {view==='settings'&&<SettingsPanel user={user} onMessage={setMessage}/>}
 {endpoints[view]&&<Card title={view==='intelligence'?'Observed threat indicators':titles[view]}>{view==='sessions'&&<div role="tablist" className="flex gap-2 mb-4">{['ACTIVE','COMPLETED'].map(s=><button key={s} role="tab" aria-selected={filters.status===s} className="gs-secondary" onClick={()=>filter('status',s)}>{s==='ACTIVE'?'Active':'Completed'}</button>)}</div>}{collection.loading?<Loading/>:<Table items={data?.items} columns={columns[view]} onOpen={open}/>}<div className="flex flex-wrap gap-3 items-center justify-between mt-4 text-xs text-slate-400"><span>{data?.total??0} records · Page {filters.page||1}</span><div className="flex gap-2"><button className="gs-secondary !py-2" disabled={Number(filters.page||1)<=1} onClick={()=>filter('page',String(Number(filters.page||1)-1))}>Previous</button><button className="gs-secondary !py-2" disabled={!data||Number(filters.page||1)*data.pageSize>=data.total} onClick={()=>filter('page',String(Number(filters.page||1)+1))}>Next</button></div></div></Card>}
 {create&&<Dialog title={view==='reports'?'Generate report':'Create ghost environment'} onClose={()=>setCreate(false)}>{message&&<p role="alert" className="text-cyan-300 text-sm">{message}</p>}<form className="space-y-4" onSubmit={e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));if(view==='reports'){data.dateFrom=new Date(data.dateFrom+'T00:00:00Z').toISOString();data.dateTo=new Date(data.dateTo+'T23:59:59.999Z').toISOString();}mutation('/api/'+endpoints[view],data);}}>{view==='reports'?<><Field name="name" label="Report name"/><Field name="reportType" label="Report type" options={['EXECUTIVE','ATTACK_BEHAVIOUR','GHOST_SESSIONS','THREAT_INTELLIGENCE','SYSTEM_HEALTH']}/><Field name="dateFrom" label="From (UTC)" type="date" defaultValue={new Date(Date.now()-7*86400000).toISOString().slice(0,10)}/><Field name="dateTo" label="To (UTC)" type="date" defaultValue={new Date().toISOString().slice(0,10)}/><Field name="dataScope" label="Data included" options={['all','simulated','real']}/></>:<EnvironmentFields record={preferences.data?.ghostDefaults||{}}/>}<button className="gs-primary" disabled={busy}>{busy?'Saving…':'Save'}</button></form></Dialog>}
 {selected&&<Dialog title={selected.name||selected.title||selected.sessionCode||'Record details'} onClose={()=>setSelected(null)}>{message&&<p role="alert" className="text-cyan-300 text-sm">{message}</p>}<Details view={view} record={selected} user={user} busy={busy} mutation={mutation} setConfirm={setConfirm}/></Dialog>}
 {confirm&&<Dialog title={confirm.title} onClose={()=>setConfirm(null)}>{message&&<p role="alert" className="text-cyan-300 text-sm">{message}</p>}<p className="text-sm text-slate-300">{confirm.description||'This action cannot be undone.'}</p><button className="gs-primary" disabled={busy} onClick={()=>mutation(confirm.url,confirm.data,confirm.method)}>{busy?'Working…':'Confirm'}</button></Dialog>}
 </div></DashboardShell>;
}
function FilterSelect({label,value,options,onChange}){return <label className="text-xs text-slate-400">{label}<select className={inputClass} value={value||''} onChange={e=>onChange(e.target.value)}><option value="">All</option>{options.map(o=><option key={o}>{o}</option>)}</select></label>}
function ChartGrid({data,intelligence=false}){return <div className="grid lg:grid-cols-2 gap-5"><Chart title="Incoming traffic over time (UTC)" data={data?.traffic} kind="area"/><Chart title="Threat severity distribution (alerts)" data={data?.severity} kind="pie"/><Chart title="Attack types" data={data?.attackTypes}/><Chart title="Most targeted services" data={data?.services}/><Chart title="Top attack locations" data={data?.locations}/><Chart title="Allowed / monitored / diverted / blocked decisions" data={data?.decisions} kind="pie"/>{intelligence&&<><Chart title="Frequently observed commands (inert text)" data={data?.commands}/><Chart title="Risk distribution" data={data?.risk} kind="pie"/></>}</div>}
function Health({data}){return <><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{data?.components.map(c=><Card key={c.name} title={c.name}><Badge>{c.status}</Badge><p className="text-sm mt-3">Health: {c.healthPercentage===null?'No observations':c.healthPercentage+'%'}</p><p className="text-xs text-slate-400 mt-2">Processed: {c.processedEventCount}<br/>Last activity: {time(c.lastActivity)}</p>{c.error&&<p role="alert">{c.error}</p>}</Card>)}</div><Card title="Ghost environment health"><Table items={data?.environments} columns={columns.environments}/></Card></>}
function EnvironmentFields({record={}}){return <><Field name="name" label="Environment name" defaultValue={record.name}/><Field name="operatingSystem" label="Operating system" defaultValue={record.operatingSystem} options={['Ubuntu 24.04','Windows Server 2022','Debian 12']}/><Field name="serviceTemplate" label="Service template" defaultValue={record.serviceTemplate} options={['HTTP','SSH','Database','Identity']}/><Field name="networkProfile" label="Network profile" options={['ISOLATED']}/><Field name="simulationLevel" label="Simulation level" defaultValue={record.simulationLevel||'MEDIUM'} options={['LOW','MEDIUM','HIGH']}/><Field name="loggingLevel" label="Logging level" defaultValue={record.loggingLevel} options={['STANDARD','VERBOSE']}/></>}
function Details({view,record:r,user,busy,mutation,setConfirm}) {
 const admin=user?.role?.toUpperCase()==='ADMIN',manage=['ADMIN','ANALYST'].includes(user?.role?.toUpperCase());const base='/api/'+endpoints[view]+'/'+r.id;
 return <>
 <div className="flex flex-wrap gap-2"><Badge>{r.simulated?'SIMULATED':'REAL / MIXED'}</Badge>{r.status&&<Badge>{r.status}</Badge>}{r.riskScore!==undefined&&<Badge>Risk {r.riskScore}</Badge>}</div>
 {view==='traffic'&&<><dl className="grid grid-cols-2 gap-3 text-sm">{['sourceIp','sourceCountry','requestPath','requestMethod','protocol','userAgent','eventType','decision','status'].map(k=><div className="min-w-0" key={k}><dt className="text-slate-500">{k}</dt><dd className="break-words">{r[k]}</dd></div>)}</dl><Card title="Decision explanation"><p className="text-sm text-slate-300">{r.riskDecision?.explanation}</p><ul className="space-y-2 mt-3 text-xs text-cyan-300">{r.riskDecision?.matchedRules?.map(rule=><li key={rule.name}>{rule.name}: +{rule.weight}</li>)}</ul></Card>{r.attackSessionId&&<Link className="text-cyan-400" href="/attack-sessions">Investigate attack sessions →</Link>}</>}
 {view==='sessions'&&<><p className="text-sm text-slate-300">{r.sourceIp} · {r.sourceCountry} · {r.attackType}</p><p className="text-xs text-slate-400">Assigned analyst: {r.assignedAnalystId===user?.id?'You':r.assignedAnalystId||'Unassigned'}</p>{manage&&<div className="flex flex-wrap gap-2"><button className="gs-secondary" disabled={busy} onClick={()=>mutation(base,{assignedAnalystId:user.id},'PATCH')}>Assign to me</button><button className="gs-secondary" disabled={busy} onClick={()=>mutation(base,{status:r.status==='COMPLETED'?'ACTIVE':'COMPLETED'},'PATCH')}>{r.status==='COMPLETED'?'Reopen session':'Complete session'}</button></div>}<a className="text-cyan-400 text-sm" href={base+'/export'}>Export timeline CSV</a><TerminalReplay logs={(r.actions||[]).filter(a=>a.simulated&&a.commandText).map(a=>({time:time(a.timestamp),command:a.commandText,output:a.result,isSuspicious:a.severity==='HIGH'||a.severity==='CRITICAL'}))} sessionTitle={r.sessionCode}/><p className="text-xs text-slate-400">Replay displays stored simulated text only. No commands are executed.</p><ActionTimeline actions={r.actions}/>{manage&&<NoteForm busy={busy} onSubmit={note=>mutation(base+'/notes',{note})}/>}</>}
 {view==='environments'&&<><p className="text-sm">CPU {r.cpuUsage}% · Memory {r.memoryUsage}% · {r.isolationStatus}</p><Card title="Active sessions"><Table items={r.activeSessions} columns={columns.sessions.slice(1,5)}/></Card>{admin&&<><div className="flex gap-2 flex-wrap"><button className="gs-primary" disabled={busy||r.status==='RUNNING'} onClick={()=>mutation(base+'/start')}>Start simulation</button><button className="gs-secondary" disabled={busy||r.status==='STOPPED'} onClick={()=>mutation(base+'/stop')}>Stop simulation</button><button className="gs-secondary" disabled={busy} onClick={()=>setConfirm({title:'Delete unused environment?',url:base,method:'DELETE',data:{confirm:true}})}>Delete</button></div><form className="space-y-4" onSubmit={e=>{e.preventDefault();mutation(base,Object.fromEntries(new FormData(e.currentTarget)),'PATCH');}}><EnvironmentFields record={r}/><button disabled={busy} className="gs-primary">Save environment</button></form></>}</>}
 {view==='alerts'&&<><p className="text-sm text-slate-300">{r.description}</p><p className="text-xs text-slate-400">Assigned analyst: {r.assignedUserId===user?.id?'You':r.assignedUserId||'Unassigned'}</p>{manage&&<><div className="flex flex-wrap gap-2"><button disabled={busy} className="gs-secondary" onClick={()=>mutation(base+'/assign',{assignedUserId:user.id})}>Assign to me</button><button disabled={busy||r.status==='RESOLVED'} className="gs-secondary" onClick={()=>mutation(base+'/acknowledge')}>Acknowledge</button>{r.status==='RESOLVED'&&<button disabled={busy} className="gs-secondary" onClick={()=>mutation(base+'/reopen')}>Reopen</button>}</div><NoteForm busy={busy} onSubmit={note=>mutation(base,{note},'PATCH')}/>{r.status!=='RESOLVED'&&<form className="space-y-3" onSubmit={e=>{e.preventDefault();mutation(base+'/resolve',Object.fromEntries(new FormData(e.currentTarget)));}}><Field name="resolutionNotes" type="textarea" label="Resolution notes"/><button disabled={busy} className="gs-primary">Resolve alert</button></form>}</>}{r.resolutionNotes&&<p className="text-sm">Resolution: {r.resolutionNotes}</p>}<Card title="Alert timeline"><ul className="space-y-3 text-xs">{r.timeline?.map(a=><li key={a.id} className="border-l border-cyan-500 pl-3"><p>{time(a.createdAt)} · {a.action}</p><p className="text-slate-400 mt-1">{a.metadata?.note||a.metadata?.resolutionNotes||a.metadata?.status||''}</p></li>)}</ul></Card></>}
 {view==='reports'&&<><div className="flex gap-3"><a className="gs-primary" href={base+'/download?format=pdf'}>Download PDF</a><a className="gs-secondary" href={base+'/download?format=csv'}>Download CSV</a>{manage&&<button className="gs-secondary" disabled={busy} onClick={()=>setConfirm({title:'Delete this report?',url:base,method:'DELETE',data:{confirm:true}})}>Delete report</button>}</div><pre className="text-xs text-slate-300 whitespace-pre-wrap break-words max-h-80 overflow-auto">{JSON.stringify(r.snapshot,null,2)}</pre></>}
 {view==='intelligence'&&<><p>{r.description}</p><p className="text-sm">Confidence {r.confidence}% · Occurrences {r.occurrenceCount}</p><p className="text-xs text-slate-400">First seen {time(r.firstSeen)}<br/>Last seen {time(r.lastSeen)}</p></>}
 </>;
}
function NoteForm({busy,onSubmit}){return <form className="space-y-3" onSubmit={e=>{e.preventDefault();onSubmit(new FormData(e.currentTarget).get('note'));}}><Field name="note" label="Investigation note" type="textarea"/><button className="gs-secondary" disabled={busy}>Add note</button></form>}
function ActionTimeline({actions}){return <Card title="Session action timeline">{actions?.length?<ul className="space-y-3 text-xs">{actions.map(a=><li key={a.id} className="border-l border-violet-500 pl-3"><p>{time(a.timestamp)} · {a.actionType} · {a.severity}</p><pre className="whitespace-pre-wrap text-slate-400 mt-1">{a.commandText}{a.commandText?'\n':''}{a.result}</pre></li>)}</ul>:<Empty>No recorded actions.</Empty>}</Card>}
