import { z } from 'zod';
export const username = z.string().trim().min(3).max(20).regex(/^[a-z0-9_.]+$/, 'Use lowercase letters, numbers, underscores and periods.');
export const email = z.string().trim().toLowerCase().email().max(254);
export const password = z.string().min(8).refine(v => new TextEncoder().encode(v).length <= 72, 'Password must be at most 72 bytes.').regex(/[A-Z]/, 'Include an uppercase letter.').regex(/[a-z]/, 'Include a lowercase letter.').regex(/[0-9]/, 'Include a number.').regex(/[^A-Za-z0-9\s]/, 'Include a special character.');
const name = z.string().trim().min(2).max(100).regex(/^[^<>\x00-\x1f]+$/, 'Enter a valid name.');
const short = z.string().trim().max(120).regex(/^[^<>\x00-\x1f]*$/).optional();
export const signupSchema = z.object({name, username, email, password, confirmPassword: z.string(), terms: z.literal(true, {error:'Accept the terms and privacy policy.'})}).refine(v=>v.password===v.confirmPassword,{path:['confirmPassword'],message:'Passwords must match.'});
export const loginSchema = z.object({email, password:z.string().min(1).max(200)});
export const completionSchema = z.object({username,jobTitle:short,organization:short,terms:z.literal(true)});
export const profileSchema = z.object({name,username,bio:z.string().trim().max(500).regex(/^[^<>\x00-\x1f]*$/).optional(),jobTitle:short,organization:short,location:short,image:z.union([z.literal(''),z.string().url().max(2048).refine(v=>new URL(v).protocol==='https:','Use an HTTPS image URL.')]).optional()});
export const passwordSchema=z.object({currentPassword:z.string().min(1).max(200),password,confirmPassword:z.string()}).refine(v=>v.password===v.confirmPassword,{path:['confirmPassword'],message:'Passwords must match.'});
