const {chromium}=require('@playwright/test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
require('@next/env').loadEnvConfig(process.cwd());
const {PrismaClient}=require('@prisma/client');
const {fixture,cleanup}=require('./platform-fixtures.cjs');
const db=new PrismaClient();const base=process.env.TEST_BASE_URL||'http://localhost:3100';
(async()=>{let browser,user;const errors=[];try{
 user=await fixture(db);browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});const page=await context.newPage();page.setDefaultTimeout(20000);page.setDefaultNavigationTimeout(20000);page.on('pageerror',e=>{errors.push(e.message);console.log('Browser error at',page.url(),e.stack);});page.on('console',m=>{if(m.type()==='error'){errors.push(m.text());console.log('Console error',m.location(),m.text());}});
 await page.goto(base+'/dashboard');await page.waitForURL('**/login');
 await page.getByLabel('Email address').fill(user.email);await page.getByLabel('Password',{exact:true}).fill(user.password);await page.getByRole('button',{name:'Sign In',exact:true}).click();await page.waitForURL('**/dashboard');await page.getByRole('heading',{name:'Security Command Center'}).waitFor();
 await page.getByRole('button',{name:'Start Simulation',exact:true}).click();await page.getByRole('status').filter({hasText:'Saved successfully.'}).waitFor();
 await page.waitForTimeout(5500);await page.getByRole('button',{name:'Stop Simulation',exact:true}).click();await page.waitForTimeout(600);
 fs.mkdirSync('test-results',{recursive:true});console.log('Dashboard loaded');await page.screenshot({path:'test-results/dashboard-desktop.png',fullPage:true,timeout:15000});
 console.log('Checking traffic');await page.goto(base+'/live-traffic');await page.getByRole('button',{name:'Open',exact:true}).first().click();await page.getByRole('heading',{name:'Decision explanation'}).waitFor();await page.getByRole('button',{name:'Close dialog'}).click();await page.getByRole('button',{name:'Pause updates',exact:true}).click();assert(await page.getByRole('button',{name:'Resume updates'}).isVisible());
 // Use a deterministic defensive fixture to guarantee a session and replay.
 await page.evaluate(async()=>{const run=async(path,data)=>{const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:JSON.stringify(data)});if(!response.ok)throw Error('Fixture failed');return response.json();};await run('/api/simulation',{action:'start',speed:10});await run('/api/simulation',{action:'stop'});});
 console.log('Checking sessions');await page.goto(base+'/attack-sessions');const replaySession=await page.evaluate(async()=>{const data=await(await fetch('/api/attack-sessions')).json();return data.items.find(s=>s.ghostEnvironmentId)?.sessionCode;});assert(replaySession,'Expected a simulated ghost session');await page.getByRole('row').filter({hasText:replaySession}).getByRole('button',{name:'Open',exact:true}).click();await page.getByText('Replay displays stored simulated text only.',{exact:false}).waitFor();
 const step=page.getByTitle('Step Forward');if(await step.count())await step.click();else await page.getByRole('button',{name:'Play'}).first().click();await page.getByText('ghost-user (simulated output)',{exact:true}).waitFor();await page.screenshot({path:'test-results/session-replay.png'});await page.getByRole('button',{name:'Close dialog'}).click();
 console.log('Checking environments');await page.goto(base+'/ghost-environments');await page.getByRole('button',{name:'Create environment'}).click();await page.getByLabel('Environment name').fill('Browser Ghost');await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.getByRole('row').filter({hasText:'Browser Ghost'}).getByRole('button',{name:'Open'}).click();await page.getByRole('button',{name:'Start simulation',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
 console.log('Checking alerts');await page.goto(base+'/alerts');await page.getByRole('button',{name:'Open',exact:true}).first().click();await page.getByRole('button',{name:'Assign to me'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.getByRole('button',{name:'Open',exact:true}).first().click();await page.getByLabel('Resolution notes').fill('Reviewed in browser test.');await page.getByRole('button',{name:'Resolve alert'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
 console.log('Checking reports');await page.goto(base+'/reports');await page.getByRole('button',{name:'Generate report'}).click();await page.getByLabel('Report name').fill('Browser report');await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.getByRole('button',{name:'Open',exact:true}).first().click();const downloadPromise=page.waitForEvent('download');await page.getByRole('link',{name:'Download PDF'}).click();const download=await downloadPromise;assert(download.suggestedFilename().endsWith('.pdf'));await page.getByRole('button',{name:'Close dialog'}).click();
 console.log('Checking settings');await page.goto(base+'/settings');await page.getByLabel('Detection sensitivity').fill('65');await page.getByRole('button',{name:'Save settings',exact:true}).click();await page.getByRole('status').filter({hasText:'Saved successfully.'}).waitFor();await page.reload();assert.equal(await page.getByLabel('Detection sensitivity').inputValue(),'65');
 console.log('Checking profile');await page.goto(base+'/profile');await page.getByLabel('Full name').fill('Updated Browser Analyst');await page.getByRole('button',{name:'Save changes'}).click();await page.getByRole('heading',{name:'Updated Browser Analyst'}).waitFor();
 for(const route of ['/threat-intelligence','/system-architecture']){await page.goto(base+route);await page.locator('h1').waitFor();await page.waitForTimeout(400);}
 await page.setViewportSize({width:390,height:844});await page.goto(base+'/dashboard');await page.getByRole('button',{name:'Open sidebar'}).click();await page.locator('aside').getByRole('link',{name:'Live Traffic'}).click();await page.waitForURL('**/live-traffic');await page.getByRole('heading',{name:'Live Traffic',exact:true,level:1}).waitFor();await page.getByRole('button',{name:'Open',exact:true}).first().waitFor();await page.screenshot({path:'test-results/traffic-mobile.png',fullPage:true});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),'Mobile page overflows viewport');
 await page.setViewportSize({width:1440,height:1000});await page.locator('header summary').click();await page.locator('header').getByRole('button',{name:'Logout',exact:true}).click();await page.waitForURL('**/login');
 assert.deepEqual(errors,[],'Critical browser console errors');console.log('PASS browser login redirect, dashboard, live traffic, replay, environment, alerts, PDF, settings/profile persistence, mobile sidebar, logout and console');
 }finally{await browser?.close();if(user)await cleanup(db,[user.id]);await db.$disconnect();}})().catch(e=>{console.error(e.message);process.exitCode=1;});
